server:
  port: 8084
spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/book-market
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
